"""
train_models.py
───────────────
Trains all ML models from the collected CSV data and saves .pkl files.

Usage:
    python train_models.py

Input:  data/system_data.csv  (generated by collect_data.py)
Output: models/ram_predictor.pkl     — RandomForest: predict next RAM %
        models/anomaly_detector.pkl  — IsolationForest: CPU/RAM anomaly
        models/process_clusterer.pkl — KMeans: process clusters
        models/resource_predictor.pkl— RandomForest: binary RAM critical alert
        models/scalers.pkl           — all StandardScalers (needed for inference)

Run this every time you collect fresh data.
"""

import pandas as pd
import numpy as np
import pickle
from pathlib import Path
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier, IsolationForest
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, classification_report

DATA_PATH   = Path("data/system_data.csv")
MODELS_DIR  = Path("models")
WINDOW_SIZE = 10   # lookback window for time-series features


def load_data():
    if not DATA_PATH.exists():
        print(f"ERROR: {DATA_PATH} not found.")
        print("Run  python collect_data.py  first to generate training data.")
        exit(1)

    df = pd.read_csv(DATA_PATH, parse_dates=["timestamp"])
    print(f"Loaded {len(df)} rows from {DATA_PATH}")
    print(f"Date range: {df['timestamp'].min()} → {df['timestamp'].max()}")
    print(f"RAM range:  {df['ram_percent'].min():.1f}% – {df['ram_percent'].max():.1f}%")
    print(f"CPU range:  {df['cpu_percent'].min():.1f}% – {df['cpu_percent'].max():.1f}%")
    return df


def build_window_features(series: np.ndarray, window: int = WINDOW_SIZE):
    """Sliding window: each row = [t-9, t-8, ..., t], target = t+1."""
    X, y = [], []
    for i in range(len(series) - window):
        X.append(series[i: i + window])
        y.append(series[i + window])
    return np.array(X), np.array(y)


def train_ram_predictor(df):
    print("\n── Training RAM Predictor (RandomForestRegressor) ──")
    ram = df["ram_percent"].values
    X, y = build_window_features(ram, WINDOW_SIZE)

    scaler = StandardScaler()
    X_s = scaler.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X_s, y, test_size=0.2, shuffle=False)

    model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
    model.fit(X_train, y_train)

    preds = model.predict(X_test)
    mae = mean_absolute_error(y_test, preds)
    print(f"  Test MAE: {mae:.3f}%  (mean absolute error in RAM %)")
    print(f"  Training samples: {len(X_train):,}  |  Test samples: {len(X_test):,}")

    return model, scaler


def train_resource_predictor(df):
    """
    Classifies: will RAM be critical (>85%) in the next 60 seconds?
    Features: current metrics + rolling averages + slopes.
    """
    print("\n── Training Resource Predictor (RandomForestClassifier) ──")

    feature_cols = [
        "cpu_percent", "ram_percent", "swap_percent",
        "cpu_1min_avg", "cpu_5min_avg",
        "ram_1min_avg", "ram_5min_avg",
        "ram_slope_30s", "cpu_slope_30s",
        "hour_of_day", "day_of_week",
    ]

    df_clean = df.dropna(subset=feature_cols + ["label_ram_critical"])
    X = df_clean[feature_cols].values
    y = df_clean["label_ram_critical"].values

    scaler = StandardScaler()
    X_s = scaler.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X_s, y, test_size=0.2, shuffle=False)

    model = RandomForestClassifier(n_estimators=100, class_weight="balanced", random_state=42, n_jobs=-1)
    model.fit(X_train, y_train)

    preds = model.predict(X_test)
    print(classification_report(y_test, preds, target_names=["Normal", "Critical"], zero_division=0))

    return model, scaler


def train_anomaly_detector(df):
    print("\n── Training Anomaly Detector (IsolationForest) ──")
    X = df[["cpu_percent", "ram_percent", "swap_percent", "cpu_1min_avg", "ram_1min_avg"]].values

    scaler = StandardScaler()
    X_s = scaler.fit_transform(X)

    model = IsolationForest(contamination=0.05, n_estimators=100, random_state=42)
    model.fit(X_s)

    scores = model.decision_function(X_s)
    n_anomalies = (model.predict(X_s) == -1).sum()
    print(f"  Training rows: {len(X):,}  |  Detected anomalies: {n_anomalies} ({100*n_anomalies/len(X):.1f}%)")
    return model, scaler


def train_process_clusterer(df):
    """
    KMeans clusters system states (not processes directly — processes
    aren't in the CSV). This gives 'system load state': Idle / Normal / High.
    The live process clustering in the UI uses the live buffer.
    """
    print("\n── Training Process Clusterer (KMeans k=3) ──")
    X = df[["cpu_percent", "ram_percent", "cpu_1min_avg", "ram_1min_avg"]].values

    scaler = StandardScaler()
    X_s = scaler.fit_transform(X)

    model = KMeans(n_clusters=3, random_state=42, n_init=10)
    labels = model.fit_predict(X_s)

    # Name clusters by centroid magnitude
    centroids  = model.cluster_centers_
    magnitudes = [np.linalg.norm(c) for c in centroids]
    sorted_ids = np.argsort(magnitudes)
    label_map  = {int(sorted_ids[0]): "Idle", int(sorted_ids[1]): "Normal", int(sorted_ids[2]): "High Load"}

    counts = {label_map[i]: (labels == i).sum() for i in range(3)}
    print(f"  Cluster distribution: {counts}")
    return model, scaler, label_map


def save_models(ram_model, ram_scaler,
                res_model, res_scaler,
                ano_model, ano_scaler,
                clu_model, clu_scaler, clu_label_map):
    MODELS_DIR.mkdir(exist_ok=True)

    def save(obj, name):
        path = MODELS_DIR / name
        with open(path, "wb") as f:
            pickle.dump(obj, f)
        size_kb = round(path.stat().st_size / 1024, 1)
        print(f"  Saved {path}  ({size_kb} KB)")

    print("\n── Saving .pkl files ──")
    save(ram_model,  "ram_predictor.pkl")
    save(res_model,  "resource_predictor.pkl")
    save(ano_model,  "anomaly_detector.pkl")
    save(clu_model,  "process_clusterer.pkl")
    save({
        "ram_scaler":     ram_scaler,
        "res_scaler":     res_scaler,
        "ano_scaler":     ano_scaler,
        "clu_scaler":     clu_scaler,
        "clu_label_map":  clu_label_map,
        "window_size":    WINDOW_SIZE,
        "res_features": [
            "cpu_percent", "ram_percent", "swap_percent",
            "cpu_1min_avg", "cpu_5min_avg",
            "ram_1min_avg", "ram_5min_avg",
            "ram_slope_30s", "cpu_slope_30s",
            "hour_of_day", "day_of_week",
        ],
    }, "scalers.pkl")


def main():
    print("=" * 55)
    print("  Smart Health Dashboard — Model Trainer")
    print("=" * 55)

    df = load_data()

    if len(df) < 50:
        print(f"\nWARNING: Only {len(df)} rows — results will be poor.")
        print("Run collect_data.py for at least 300s for decent results.")

    ram_model,  ram_scaler               = train_ram_predictor(df)
    res_model,  res_scaler               = train_resource_predictor(df)
    ano_model,  ano_scaler               = train_anomaly_detector(df)
    clu_model,  clu_scaler, clu_label_map = train_process_clusterer(df)

    save_models(ram_model, ram_scaler,
                res_model, res_scaler,
                ano_model, ano_scaler,
                clu_model, clu_scaler, clu_label_map)

    print("\n✓ All models trained and saved.")
    print("Next step: run  python main.py  to launch the dashboard.")


if __name__ == "__main__":
    main()
